### ISSUE TITLE
[Question] Cross Platform

### ISSUE THREAD

**Issue by darderik** [overfl0/Pythia#15]
Will this project be able to run on Linux for the 1.0 Release?

**Comment by overfl0** [comment]
Hello,

that's a hard question to answer due to several reasons.
Of course, I would like for the extension to be fully cross-platform and, ideally, be able to support both windows and linux (linux server + linux client) and I'd be more than happy to receive pull requests that would help with porting Pythia to linux.

Instead of answering directly, let me lay down the current situation.

The Pythia development has slowed down considerably over the last few months due to a few things.
I've been working on several separate functionalities on separate branches and have not yet finished either of them so that they have not ended in the master branch.
Another cause for that is that Pythia is a means to an end: writing code for Arma in Python. Hence, I've put the work on Pythia itself on hold as it's now "good enough" to actually start writing something and focused on creating a new game mode for Frontline , my PvP group that I'm part of.

The new game mode (besides being something that the Arma community has never seen yet ;) ) is partly a proof of concept that will prove that Pythia is really working and also will test the extension itself and help in figuring out missing functionality that needs to be added to Pythia (and it shall be added as it is found).

As the group is using windows servers, I have (currently!) no need to make it work on linux, and due to the limited free time I have, I simply cannot afford spending my time on that feature. Also, looking at how OpenSource communities work, it's a much better bet to spend the time to develop a good extension that would then attract other people willing to help (with implementing linux support, for example).

Another thing to also keep in mind is that Intercept is gaining speed lately and I'm closely monitoring and even helping the project because when Intercept becomes stable and with a guarantee of being maintained, any other python/ruby/whatever extensions will become obsolete.

As I will then move my own code and mods to Intercept, I'm planning to make sure that the interface will be as compatible as possible with Intercept itself so that porting the code is simple and easy. And maybe even make it so that Pythia could be used as a (limited) fallback in case Intercept-python stops working after an Arma update.

If you have more questions, feel free to ask. You can also join [Frontline's Discord](discord.frontline.frl) to chat, if you're interested.
