### ISSUE TITLE
Could you add the fuction to run .py scripts in the mission path?

### ISSUE THREAD

**Issue by gytjd01122** [overfl0/Pythia#46]

**Comment by gytjd01122** [comment]
mission path can get using [this command](https://community.bistudio.com/wiki/getMissionPath)

**Comment by overfl0** [comment]
Hi @gytjd01122 , first sorry for the late reply. I'm currently working on a CDLC for Arma and I cannot devote as much time as I would like to to my mods.

Why do you really need such a feature? The last time someone was asking for it was because they needed to be able so easily reload the code, while developing.
If that's what you want, then adding reading code from missions is not going to work the way you want and the python code in memory will stay as is, until you manually reload it, anyway.

To develop your mod, it's best to place your code in a module (as explained in the readme) and use the Pythia code reloader instead: https://github.com/overfl0/Pythia#code-reloader

----

Other than that I see more problems than benefits with having code in your mission path.

The biggest problem is that missions may be loaded and unloaded but the python code will stay loaded (forever). This may lead to surprises for the mission maker, who expected to have the namespace to be empty but finds that it contains old variables from the last time the same mission was run, in the memory.
Having the python code in a mod ensures it is clear that the code will stay in memory until Arma is closed.

Also, some other questions would have to be answered, like in what namespace to store the variables created by the code from the mission? The global namespace or something special? If global, then variable names may clash. And if not then what name? Etc...

There is an obscure python feature that could (in theory) help, which is subinterpreters per mission, maybe, but it's something that's not really used and normal access to the subinterpreters is planned to be added to python 3.10. Until now, the only way to access them was by directly calling C functions, from the cpython library.

All in all, it probably could be done, but I think the current state of Pythia makes it safer to write code that will not surprise you.

**Comment by overfl0** [comment]
I'm going to close this issue because I don't think there currently is a reasonable way to implement this while making sure everything will work correctly when the mission restarts. Thanks for your input, though :)
